### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by tand22** [mantiumai/aws-sagemaker-gptj-deepspeed-blog#1]
Getting the following when trying to invoke a request while the container is running locally.

```
ERROR:predictor:Exception on /invocations [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/program/predictor.py", line 148, in transformation
    predictions = ScoringService.predict(inputs)
  File "/opt/program/predictor.py", line 115, in predict
    pipe = cls.get_pipeline()
  File "/opt/program/predictor.py", line 68, in get_pipeline
    model = no_init(lambda: AutoModelForCausalLM.from_pretrained(
  File "/opt/program/predictor.py", line 47, in no_init
    result = loading_code()
  File "/opt/program/predictor.py", line 68, in <lambda>
    model = no_init(lambda: AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 418, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 582, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 552, in get_config_dict
    configuration_file = get_configuration_file(
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 843, in get_configuration_file
    all_files = get_list_of_files(
  File "/opt/conda/lib/python3.8/site-packages/transformers/file_utils.py", line 2103, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1361, in list_repo_files
    repo_info = self.repo_info(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1315, in repo_info
    return self.model_info(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 1195, in model_info
    r.raise_for_status()
  File "/opt/conda/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/None/revision/float16
172.17.0.1 - - [20/Jun/2022:12:16:22 +0000] "POST /invocations HTTP/1.1" 500 265 "-" "python-requests/2.25.1"
```

**Comment by joehoover** [comment]
Thanks for opening the issue @tand22. 

From the traceback, it looks like the local path to the model weights is not defined. The error you've observed is thrown because `AutoModel.from_pretrained()`, which is called on line 47 of `predictor.py`, is trying to download model weights from `https://huggingface.co/api/models/None/revision/float16`. 

To run the container locally, you need to download the model weights and store them in `./run_local/test_dir/`. You can use the bash script provided in the repo for that or you can download them via whatever method you prefer. 

Could you confirm that you've downloaded the model weights and stored them in the expected location? In the meantime, I'll try to reproduce the error.
